# Generated by Django 4.2.6 on 2023-10-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customername', models.CharField(default='asiakas', max_length=50)),
                ('contactname', models.CharField(default='asiakas', max_length=50)),
                ('addres', models.CharField(default='asiakas', max_length=100)),
                ('phone', models.CharField(default='asiakas', max_length=20)),
                ('email', models.CharField(default='asiakas', max_length=50)),
                ('country', models.CharField(default='asiakas', max_length=50)),
            ],
        ),
    ]
