# Generated by Django 4.2.6 on 2023-10-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storename', models.CharField(default='kauppa', max_length=20)),
                ('contactname', models.CharField(default='kauppa', max_length=50)),
                ('addres', models.CharField(default='kauppa', max_length=100)),
                ('phone', models.CharField(default='kauppa', max_length=20)),
                ('email', models.CharField(default='kauppa', max_length=50)),
                ('country', models.CharField(default='kauppa', max_length=50)),
            ],
        ),
    ]
